---
# tasks file for wordpress
- name: Download WordPress
  get_url:
   url=https://wordpress.org/latest.tar.gz
   dest=/tmp/wordpress.tar.gz
   validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Update default Apache site
  lineinfile:
   dest=/etc/apache2/sites-enabled/000-default.conf
   regexp="(.)+DocumentRoot /var/www/html"
   line="DocumentRoot /var/www/wordpress"
  notify:
  - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

- name: Update Wordpress config file
  shell: |
    sed -i " s/define( 'DB_NAME'.*/define('DB_NAME', '{{wp_mysql_db}}'); /g; " /var/www/wordpress/wp-config.php
    sed -i " s/define( 'DB_USER'.*/define('DB_USER', '{{wp_mysql_user}}');/g; " /var/www/wordpress/wp-config.php 
    sed -i " s/define( 'DB_PASSWORD'.*/define( 'DB_PASSWORD', '{{wp_mysql_password}}');/g; " /var/www/wordpress/wp-config.php
  tags: [config]