---

# tasks file for server
# tasks file for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install required software
  apt: name={{ item }} state=present
  with_items:
  - apache2
  - mysql-server
  - php7.4-mysql
  - php7.4
  - libapache2-mod-php7.4
  - python3-mysqldb
